kind: pipeline
type: docker
name: default
clone:
  disable: true

steps:
  - name: clone-code
    image: alpine/git
    pull: if-not-exists # 如果在本地缓存中找不到image，则仅拉取image
    commands:
      - git config --global http.version HTTP/1.1
      - git clone https://github.com/one-thing-one-world/nest-end.git
      - git version

  - name: install deps
    image: node:16
    pull: always
    commands:
      - pwd
      - cd nest-end
      - node -v
      - yarn
      - ls
      - pwd

  - name: upload
    image: appleboy/drone-scp
    pull: always
    settings:
      debug: true
      source:
        - nest-end/
      host:
        from_secret: docker_host
      username:
        from_secret: docker_username
      port: 22
      password:
        from_secret: docker_password
      target: /root/end_workspace

      when:
        branch:
          include:
            - master
        event:
          - push
          - merge
      script:
        - echo "hello deploy"
        - ls
        - pwd
        - echo upload success ===>

  - name: sshs
    image: appleboy/drone-ssh
    pull: always
    settings:
      host:
        from_secret: docker_host
      username:
        from_secret: docker_username
      port: 22
      password:
        from_secret: docker_password
      script:
        - ls
        - pwd
        - cd end_workspace/nest-end/
        - ls
        - docker build -t deployend .
        - echo 'deploy successs ===>'
        - docker run  -i -p 3000:3000 deployend
        - echo 'run successs. ===>'

trigger:
  branch:
    include:
      - master
  event:
    include:
      - push
