vertion: '3.0'

services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    restart: on-failure
    environment:
      MUSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123456

    valumes:
      - ./deploy_setting/mysql/db:/var/lib/mysql # 用来存放了数据库表文件
      - ./deploy_setting/mysql/conf/my.cnf:/etc/my.cnf # 存放自定义的配置文件
      - ./deploy_setting/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - my-server
  server:
    container_name: server
    build:
      context:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: on-failure
    networks:
      - my-server
    depends_on:
      - mysql
networks:
  my-server:
