version: '3.0'

services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password

    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: book
    volumes:
      - ./deploy_setting/mysql/db:/var/lib/mysql # 用来存放了数据库表文件.
      # - ./deploy_setting/mysql/conf/my.cnf:/etc/my.cnf # 存放自定义的配置文件
      # - ./deploy_setting/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - my-net

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm run start:dev'
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db

    networks:
      - my-net

networks:
  my-net:
